site_name: Machine Controller Docs
site_url: http://localhost/mydocs/

theme:
  name: material
  language: en
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - styles/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Overview:
    - Home: index.md
    - Setup: settingup.md
    - Architecture: architecture.md
    - Examples: example.md
  - Modules:
    - Machine: modules/machine.md
    - SerialConnection: modules/serialconnection.md
    - CameraRepo: modules/camerarepo.md
    - Device: modules/device.md
    - MachineController: modules/machinecontroller.md
    - Empty: modules/empty.md
  - Web:
    - Empty: web/empty.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
      timezone: Asia/Kuala_Lumpur  # Adjust to your region
      locale: en
  - git-authors
